# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class NewModelElement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None, param=None):  # noqa: E501
        """NewModelElement - a model defined in OpenAPI

        :param name: The name of this NewModelElement.  # noqa: E501
        :type name: str
        :param type: The type of this NewModelElement.  # noqa: E501
        :type type: str
        :param param: The param of this NewModelElement.  # noqa: E501
        :type param: object
        """
        self.openapi_types = {
            'name': str,
            'type': str,
            'param': object
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'param': 'param'
        }

        self._name = name
        self._type = type
        self._param = param

    @classmethod
    def from_dict(cls, dikt) -> 'NewModelElement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewModelElement of this NewModelElement.  # noqa: E501
        :rtype: NewModelElement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this NewModelElement.

        Name of model element  # noqa: E501

        :return: The name of this NewModelElement.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NewModelElement.

        Name of model element  # noqa: E501

        :param name: The name of this NewModelElement.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this NewModelElement.

        CIM type of model element  # noqa: E501

        :return: The type of this NewModelElement.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NewModelElement.

        CIM type of model element  # noqa: E501

        :param type: The type of this NewModelElement.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def param(self):
        """Gets the param of this NewModelElement.

        Element attributes, e.g. strings and numbers  # noqa: E501

        :return: The param of this NewModelElement.
        :rtype: object
        """
        return self._param

    @param.setter
    def param(self, param):
        """Sets the param of this NewModelElement.

        Element attributes, e.g. strings and numbers  # noqa: E501

        :param param: The param of this NewModelElement.
        :type param: object
        """

        self._param = param
